version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: psql_2
    environment:
      POSTGRES_USER: linktic_user
      POSTGRES_PASSWORD: w6T07nT4P4Lo
      POSTGRES_DB: technical_assessment_db
    ports:
      - "5432:5432" # Izquierda: Tu PC (5433), Derecha: Interno (5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: